# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9764a826900b0263dfd0970bcf0b93e0f91c9f00114f0067d8a814fa4eb92abdcd5180ce1133fbd623c42fa0b928e3cb103540289ceacb49b1087f919e183f07

test:
  secret_key_base: 72f22ce35b83fcdb02c04ed6cf1cf697c4c9d623298f06ce161c7a5b965d5b4003ee70d6b98e9647bc5ac27413dc10016f55f1dac10fab139dd52ae9960d7ac7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
